name: Spacegame.Web
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  BUILD:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$GITHUB_WORKSPACE/TestResults/Coverage/      

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: space-web
        path: ${{github.workspace}}/Tailspin.SpaceGame.Web/bin/Release/netcoreapp3.1/publish

#---------------
  DEPLOY:
    name: Deploy
    runs-on: ubuntu-latest
    needs: BUILD
    steps:
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: space-web
        path: ${{github.workspace}}
