name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - run: ls ${{github.workspace}}
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet publish -c Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=${{github.workspace}}/TestResults/Coverage/          
    
    - run: ls ${{github.workspace}}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: spacegame
        path: ${{github.workspace}}/Tailspin.SpaceGame.Web/bin/Release/netcoreapp3.1/publish
#-----------------------------------------------    
  DEPLOY:
    name: Deploy
    runs-on: windows-latest
    needs: build
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        name: spacegame
        path: ${{github.workspace}}
 
    - run: ls ${{github.workspace}}\stagingdir\
    - name: Azure WebApp Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: tailspinweb
        publish-profile: ${{secrets.PUBLISH_PROFILE}}
