name: TailsSPace self hosted Deploy

on:
  push:
    branches:
      - self-hosted

env:
  app_pool_name: tailswebpool
  app_name: tails

jobs:
  BUILD:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet publish -c Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$GITHUB_WORKSPACE/TestResults/Coverage/      

    - name: Upload artifact
      uses: actions/upload-artifact@2.1.0
      with:
        name: space-web
        path: |
          ${{github.workspace}}/Tailspin.SpaceGame.Web/bin/Release/netcoreapp3.1/publish
          ${{github.workspace}}/*.ps1

#------------------
  DEPLOY:
    name: Deploy
    runs-on: windows-gangavali
    needs: BUILD
    steps:
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        name: space-web
        path: ${{github.workspace}}
    
    - name: Run Powershell
      run: |
        & '${{github.workspace}}\app_pool.ps1' -pool_name ${{env.app_pool_name}} -app_name ${{env.app_name}} -workspace ${{github.workspace}}
       